# Ansible playbooks level simple variables
 
config_dest: /etc/httpd/conf.d/example.conf 
web_dest: /var/www/html
doc_root_location: /var/www/html
http_port: 80
color: pink
dbpass: sujin
dbuser: tom
item:
  - php
  - php-cli
  - php-gd

