---
    - ansible.builtin.import_tasks: apache2.yaml
      vars:
        state: present
    - ansible.builtin.import_tasks: mysql2.yaml
      vars:
        state: present
    - ansible.builtin.import_tasks: php.yaml
      vars:
        state: present
    - name: "User creation"
      ansible.builtin.user:
        name: tom
        shell: /bin/bash
        uid:  50012
        password: "{{ 'password' | password_hash('sha256') }}"

    - name: Copy config file
      ansible.builtin.template:
        src: templates/example.com.j2
        dest: "{{config_dest}}"

    - name: Copy index file
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{doc_root_location}}/index.html"
        mode: 0644

