---
- name: Installing mysql webserver
  ansible.builtin.yum:
    name: mysql-server
    state: installed
  with_items:
    - bundler
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb
    - python3-mysqldb
    - python3-pip
    - MySQL-python
 
- name: Set discovered Ansible Python interpreter.
  set_fact:
    ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
  when: ansible_python_interpreter is not defined

- name: Update mysql root password for all root accounts "{{ dbpass }}"
  mysql_user: name=root password="{{ dbpass }}" priv="*.*:ALL,GRANT"


- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/tom/.my.cnf owner=root mode=0600
  notify: Restart the MySQL service

- name: Add deploy DB user
  mysql_user: name={{ dbuser }} password={{ dbpass }} priv=*.*:ALL,GRANT state=present
  notify: Restart the MySQL service

#- name: grant privilege on "{{ dbname }}" to "{{ dbuser }}"
#  mysql_user:
#    name: "{{ item.user }}"
#    host: "{{ item.host }}"
#    password: "{{ dbpass }}"
#    priv: "*.*:ALL"
#    state: present
#  with_items:
#    - { user: "{{ dbuser }}" , host: localhost }
#    - { user: "{{ dbuser }}" , host: 127.0.0.1 }


